### ISSUE TITLE
Add deployment tests to appengine

### ISSUE THREAD

**Issue by bign8** [bign8/chive-show#6]
| Problem | [Continuous Deployment](https://en.wikipedia.org/wiki/Continuous_delivery) is a neat idea |
| :-- | :-- |
| Solution | Use [Travis CI](https://travis-ci.org/bign8/chive-show) to help automate deployment |
| Status | Staging |
| Build | [![Build Status](https://travis-ci.org/bign8/chive-show.svg?branch=ci)](https://travis-ci.org/bign8/chive-show) [![codecov.io](http://codecov.io/github/bign8/chive-show/coverage.svg)](http://codecov.io/github/bign8/chive-show) |
### TODO
- [ ] Deploy to App Engine as release candidate
- [ ] Run deploy tests on App Engine release candidate
  - [ ] API request `/api/v1/random`
  - [ ] Index serving
  - [ ] Static assets (referenced by index) serving
  - [ ] Crawl site (ensure no 404s)
