### ISSUE TITLE
Add deployment tests to appengine

### ISSUE THREAD

**Issue by bign8** [bign8/chive-show#7]
| Problem | Automatic deployments can really damage the datastore |
| :-- | :-- |
| Solution | Build structure necessary to ensure production datastore cleanliness |
| Status | Staging |
| Build | [![Build Status](https://travis-ci.org/bign8/chive-show.svg?branch=ci)](https://travis-ci.org/bign8/chive-show) [![codecov.io](http://codecov.io/github/bign8/chive-show/coverage.svg)](http://codecov.io/github/bign8/chive-show) |
### TODO
- [ ] Ensure proper DB versioning + prevent db migration errors
  - [ ] Wrap [request contexts](https://cloud.google.com/appengine/docs/go/reference#Namespace) with a deployed [version identifier](https://cloud.google.com/appengine/docs/go/reference#VersionID) as a key [namespace](https://cloud.google.com/appengine/docs/go/datastore/reference#Key.Namespace)
- [ ] Tap a DB rollover script
  - [ ] Update db with current version from older namespaces
  - [ ] Allow incremental (cron based) updates to ensure not exceeding GAE limits
  - [ ] Make api executable so integration tests can run on them

_Another possibility is to abstract datastore and not write, but softly persist modifying changes to development stores_
